# Generated by Django 5.2.11 on 2026-03-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='my_field_name',
        ),
    ]
