# Generated by Django 5.2.11 on 2026-03-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_remove_event_my_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
