# Generated by Django 5.2.11 on 2026-03-01 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_organization_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
