# Generated by Django 5.2.11 on 2026-03-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_event_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'permissions': (('can_mark_cancelled', 'Set event as cancelled'),)},
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
