# Generated by Django 5.2.11 on 2026-03-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_alter_event_options_event_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
